### ISSUE TITLE
Fiat issues when running on K8s

### ISSUE THREAD

**Issue by veeresh1982** [spinnaker/fiat#173]
1) My Goal: Setup Fiat Authorization on Spinnaker which is running using K8s

2) Pre-Setup: 
------------------
a) fiat when disabled: All Spinnaker services running properly and already set the Authentication of Spinnaker using SAML and I am able to sign-on using Veeresh.Hiremath and get to Spinnaker login page. Works fine

3) fiat when enabled: 
------------------
  - see errors in front50, orca and fiat < all this 3 pods shows 0/1> when i do get 'kubectl get po'
   - fiat quay image being used: v0.25.0

below are my configs:

a)
fiat-local.yml:< This below info I also verifed using a ldap tool - JXplorer/Apache Directory studio and my below details matches from here
CN=Veeresh Hiremath,OU=People,DC=community,DC=yyyy,DC=com
OU=People,DC=community,DC=yyyy,DC=com

logging:
  level:
    com.netflix.spinnaker.fiat: DEBUG
auth:
  groupMembership:
    service: ldap
    ldap:
      url: "ldaps://vldap-prod.community.veritas.com:636/dc=community,dc=veritas,dc=com"
      managerDn: "cn=ads.cicd.bind,ou=Non-Privileged_Standard,ou=Service Accounts,dc=community,dc=veritas,dc=com"
      managerPassword: "u84DRuFrakuzu*ru"
      userDnPattern: "cn={0},ou=People"
      groupSearchBase: "ou=Groups"
      groupSearchFilter: "(member=CN={0},OU=People,DC=community,DC=veritas,DC=com)"
      groupRoleAttributes: "cn"

b)
settings.js: fiat enabled

4) Logs
Front50 logs: ( uses AWS S3 storage)
------------------
2017-04-21 19:30:53.931  INFO 1 --- [0.0-8080-exec-9] o.s.b.a.audit.listener.AuditListener     : AuditEvent [timestamp=Fri Apr 21 19:30:53 UTC 2017, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]

Orca logs:
------------------
2017-04-21 19:31:47.014  INFO 1 --- [0.0-8083-exec-4] o.s.b.a.audit.listener.AuditListener     : [] AuditEvent [timestamp=Fri Apr 21 19:31:47 UTC 2017, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]

Fiat logs:
------------------
2017-04-21 19:23:13.297 DEBUG 1 --- [pool-1-thread-1] c.n.s.f.providers.internal.Front50Api    : java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)

2017-04-21 19:23:13.300 DEBUG 1 --- [pool-1-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : User permission sync failed. Server status is DOWN. Trying again in 10000
 ms. Cause:retrofit.RetrofitError: connect timed out

com.netflix.spinnaker.fiat.providers.ProviderException: retrofit.RetrofitError: connect timed out

2017-04-21 19:32:28.401 DEBUG 1 --- [0.0-7003-exec-6] c.n.s.f.shared.FiatAuthenticationFilter  : Set SecurityContext to user: anonymous
2017-04-21 19:32:33.734 DEBUG 1 --- [pool-1-thread-1] c.n.s.f.providers.internal.Front50Api    : ---> HTTP GET http://spin-front50.spinnaker:8080/serviceAccounts
2017-04-21 19:32:38.401 DEBUG 1 --- [0.0-7003-exec-7] c.n.s.f.shared.FiatAuthenticationFilter  : Set SecurityContext to user: anonymous

5) fiat checks
------------------
root@spin-fiat-v000-xjfr5:/workdir# curl localhost:7003/health
{
  "status" : "DOWN",
  "resourceProviders" : {
    "status" : "DOWN",
    "DefaultAccountProvider" : {
      "providerHealthy" : false,
      "failureCountSinceLastSuccess" : -1
    },
    "DefaultApplicationProvider" : {
      "providerHealthy" : false,
      "failureCountSinceLastSuccess" : -1
    },
    "DefaultServiceAccountProvider" : {
      "providerHealthy" : false,
      "failureCountSinceLastSuccess" : -1
    }
  },

**Comment by veeresh1982** [comment]
When I tested with a tool ( Apache Directory studio) with below 
Search Base: OU=Groups,DC=community,DC=yyyy,DC=com  ;  Filter: (member=CN=Veeresh Hiremath,OU=People,DC=community,DC=yyyy,DC=com), I can see 34 CN records are return. So not sure if I need to have a dedicated group under BASE:Groups ( which I don't have it now for our team)

**Comment by ttomsu** [comment]
Thanks for the detailed report! 

Specifically, the line:

> com.netflix.spinnaker.fiat.providers.ProviderException: retrofit.RetrofitError: connect timed out

Indicates (usually) that Fiat cannot connect to either Front50 or Clouddriver upon startup. Could you paste in the whole stack trace (because it looks like you already have `logging.level.com.netflix.spinnaker.fiat: DEBUG` turned on.

**Comment by veeresh1982** [comment]
1) 
root@veeresh-fiat:~/spinnaker/experimental/kubernetes/simple# kubectl get po
NAME                           READY     STATUS    RESTARTS   AGE
data-redis-master-v000-jbx0q   1/1       Running   0          5d
spin-clouddriver-v000-hj5gd    1/1       Running   0          17h
spin-deck-v000-dkhxf           1/1       Running   0          20h
spin-echo-v000-nkjz8           1/1       Running   0          4d
spin-fiat-v000-1kmbk           0/1       Running   0          11m
spin-front50-v000-36q5s        0/1       Running   0          15h
spin-gate-v000-dl94x           1/1       Running   0          20h
spin-igor-v000-c4m4w           1/1       Running   0          4d
spin-orca-v000-3gx8h           1/1       Running   0          20h


2) All errors I see is for below two lines
2017-04-25 15:09:06.264 DEBUG 1 --- [pool-1-thread-1] c.n.s.f.providers.internal.Front50Api    : ---- ERROR http://spin-front50.spinnaker:8080/serviceAccounts
2017-04-25 15:03:40.994 DEBUG 1 --- [pool-1-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : User permission sync failed. Server status is DOWN. Trying again in 10000 ms. Cause:(
Provider: DefaultServiceAccountProvider) retrofit.RetrofitError: connect timed out

3) I created service accounts in Front50 using curl command like below and did a role sync. I will try to redo this steps
$ curl -X POST \
-H "Content-type: application/json" \
-d '{"name":"myApp-svc-account@group.net"}' \
front50:8080/serviceAccounts

4) MY ldap query which I can see groups/cns being returned 
DC=community,DC=yyyy,DC=com <search-base>
(member=CN=Veeresh Hiremath,OU=People,DC=community,DC=yyyy, DC=com)  <search-filter>
cn <returning attribute>

However my actual LDAP groups are under : groups are under : OU=Groups,DC=community,DC=veritas,DC=com and if use below search query < both returns 0 records>
(&(objectClass=groupOfNames)(member="CN=Veeresh Hiremath,OU=People,DC=community,DC=yyyy,DC=com"))
 "(&(objectClass=groupOfUniqueNames)(uniqueMember="CN=Veeresh Hiremath,OU=People,DC=community,DC=yyyy,DC=com"))";

$ curl -X POST localhost:7003/roles/sync

2)Fiat Logs: Below full stacktrace
017-04-25 15:03:25.861  INFO 1 --- [           main] com.netflix.spinnaker.fiat.Main          : Started Main in 5.187 seconds (JVM running for 5.465)
2017-04-25 15:03:25.869 DEBUG 1 --- [pool-1-thread-1] c.n.s.f.providers.internal.Front50Api    : ---> HTTP GET http://spin-front50.spinnaker:8080/serviceAccounts
2017-04-25 15:03:40.396 DEBUG 1 --- [0.0-7003-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing servlet 'dispatcherServlet'
2017-04-25 15:03:40.429 DEBUG 1 --- [0.0-7003-exec-1] c.n.s.f.shared.FiatAuthenticationFilter  : Set SecurityContext to user: anonymous
2017-04-25 15:03:40.437 DEBUG 1 --- [0.0-7003-exec-1] o.s.s.w.a.AnonymousAuthenticationFilter  : Populated SecurityContextHolder with anonymous token: 'org.springframework.security.a
uthentication.AnonymousAuthenticationToken@6faad796: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication
.WebAuthenticationDetails@ffffa64e: RemoteIpAddress: 10.3.73.1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS'
2017-04-25 15:03:40.442 DEBUG 1 --- [0.0-7003-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorization successful
2017-04-25 15:03:40.520 DEBUG 1 --- [0.0-7003-exec-1] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Written [DOWN {resourceProviders=DOWN {DefaultAccountProvider=ProviderHealthTracker.H
ealthView(providerHealthy=false, failureCountSinceLastSuccess=-1), DefaultApplicationProvider=ProviderHealthTracker.HealthView(providerHealthy=false, failureCountSinceLastSuccess=-1)
, DefaultServiceAccountProvider=ProviderHealthTracker.HealthView(providerHealthy=false, failureCountSinceLastSuccess=-1)}, redisHealth=UP {maxIdle=8, minIdle=0, numActive=0, numIdle=
1, numWaiters=0}, diskSpace=UP {free=155987394560, threshold=10485760}}] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessage
Converter@11fcad7f]
2017-04-25 15:03:40.521 DEBUG 1 --- [0.0-7003-exec-1] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2017-04-25 15:03:40.989 DEBUG 1 --- [pool-1-thread-1] c.n.s.f.providers.internal.Front50Api    : ---- ERROR http://spin-front50.spinnaker:8080/serviceAccounts
2017-04-25 15:03:40.990 DEBUG 1 --- [pool-1-thread-1] c.n.s.f.providers.internal.Front50Api    : java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
--More--
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:101)
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:137)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.netflix.spinnaker.fiat.config.RetrofitConfig$RetryingInterceptor.intercept(RetrofitConfig.java:117)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at retrofit.client.OkClient.execute(OkClient.java:53)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at com.sun.proxy.$Proxy69.getAllServiceAccounts(Unknown Source)
        at com.netflix.spinnaker.fiat.providers.internal.Front50Service.getAllServiceAccounts(Front50Service.java:39)
        at com.netflix.spinnaker.fiat.providers.DefaultServiceAccountProvider.loadAll(DefaultServiceAccountProvider.java:49)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4790)
        at com.netflix.spinnaker.fiat.providers.BaseProvider.getAll(BaseProvider.java:73)
        at com.netflix.spinnaker.fiat.roles.UserRolesSyncer.getServiceAccountsAsMap(UserRolesSyncer.java:136)
        at com.netflix.spinnaker.fiat.roles.UserRolesSyncer.syncAndReturn(UserRolesSyncer.java:94)
        at com.netflix.spinnaker.fiat.roles.UserRolesSyncer.sync(UserRolesSyncer.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2017-04-25 15:03:40.990 DEBUG 1 --- [pool-1-thread-1] c.n.s.f.providers.internal.Front50Api    : ---- END ERROR
2017-04-25 15:03:40.994 DEBUG 1 --- [pool-1-thread-1] c.n.s.fiat.roles.UserRolesSyncer         : User permission sync failed. Server status is DOWN. Trying again in 10000 ms. Cause:(
Provider: DefaultServiceAccountProvider) retrofit.RetrofitError: connect timed out
com.netflix.spinnaker.fiat.providers.ProviderException: (Provider: DefaultServiceAccountProvider) retrofit.RetrofitError: connect timed out
        at com.netflix.spinnaker.fiat.providers.BaseProvider.getAll(BaseProvider.java:75)
        at com.netflix.spinnaker.fiat.roles.UserRolesSyncer.getServiceAccountsAsMap(UserRolesSyncer.java:136)
        at com.netflix.spinnaker.fiat.roles.UserRolesSyncer.syncAndReturn(UserRolesSyncer.java:94)
        at com.netflix.spinnaker.fiat.roles.UserRolesSyncer.sync(UserRolesSyncer.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: retrofit.RetrofitError: connect timed out
        at retrofit.RetrofitError.networkError(RetrofitError.java:27)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
        at com.sun.proxy.$Proxy69.getAllServiceAccounts(Unknown Source)
        at com.netflix.spinnaker.fiat.providers.internal.Front50Service.getAllServiceAccounts(Front50Service.java:39)
        at com.netflix.spinnaker.fiat.providers.DefaultServiceAccountProvider.loadAll(DefaultServiceAccountProvider.java:49)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4790)
        at com.netflix.spinnaker.fiat.providers.BaseProvider.getAll(BaseProvider.java:73)
        ... 16 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:101)
        at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:137)
        at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
        at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.squareup.okhttp.Call.getResponse(Call.java:286)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.netflix.spinnaker.fiat.config.RetrofitConfig$RetryingInterceptor.intercept(RetrofitConfig.java:117)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at retrofit.client.OkClient.execute(OkClient.java:53)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
 ... 28 common frames omitted

**Comment by ttomsu** [comment]
As expected, this is a Front50 connection issue, not a Fiat issue. I'm going to close this now, and if you have additional issues with the LDAP stuff (after contacting your LDAP admins), please reopen a different bug

**Comment by veeresh1982** [comment]
@ttomsu :Sure. Thanks.
