### ISSUE TITLE
Access to newly created applications is denied until roles are sync'ed manually

### ISSUE THREAD

**Issue by emptywee** [spinnaker/fiat#179]
Travis asked to file it for him.

Stack trace:

```
2017-06-05 17:13:21.764 ERROR 1 --- [0.0-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is groovy.lang.MissingPropertyException: No such property: requiredGroupMembership for class: com.netflix.spinnaker.front50.model.application.Application] with root cause

groovy.lang.MissingPropertyException: No such property: requiredGroupMembership for class: com.netflix.spinnaker.front50.model.application.Application
        at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:1004)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1859)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1835)
        at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3735)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:175)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:456)
        at com.netflix.spinnaker.front50.model.application.Application$Permission.propertyMissing(Application.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaClassImpl.invokeMissingProperty(MetaClassImpl.java:880)
        at groovy.lang.MetaClassImpl$12.getProperty(MetaClassImpl.java:2026)
        at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:85)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
        at com.netflix.spinnaker.front50.controllers.PermissionsController.syncUsers(PermissionsController.groovy:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at com.netflix.spinnaker.front50.controllers.PermissionsController.updateApplicationPermission(PermissionsController.groovy:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:775)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:965)
        at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:878)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:651)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:841)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:300)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.netflix.spinnaker.fiat.shared.FiatAuthenticationFilter.doFilter(FiatAuthenticationFilter.java:54)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at javax.servlet.FilterChain$doFilter.call(Unknown Source)
        at com.netflix.spinnaker.front50.filters.SimpleCORSFilter.doFilter(SimpleCORSFilter.groovy:38)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at javax.servlet.FilterChain$doFilter.call(Unknown Source)
        at com.netflix.spinnaker.filters.AuthenticatedRequestFilter.doFilter(AuthenticatedRequestFilter.groovy:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

```

Orca shows:

```
[spin-orca-0] 2017-06-05 17:13:21.779  INFO 1 --- [hTaskExecutor-1] c.n.s.orca.front50.Front50Service        : [user1] <--- HTTP 500 http://spin-front50:8080/permissions/applications/test4 (1067ms)
[spin-orca-0] 2017-06-05 17:13:21.790 ERROR 1 --- [hTaskExecutor-1] c.n.s.o.a.tasks.UpsertApplicationTask    : [user1] Could not create or update application permission
[spin-orca-0] retrofit.RetrofitError: 500 Internal Server Error
[spin-orca-0] at retrofit.RetrofitError.httpError(RetrofitError.java:40)
[spin-orca-0] at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
[spin-orca-0] at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
[spin-orca-0] at com.sun.proxy.$Proxy91.updatePermission(Unknown Source)
[spin-orca-0] at com.netflix.spinnaker.orca.applications.tasks.UpsertApplicationTask.performRequest(UpsertApplicationTask.groovy:50)
[spin-orca-0] at com.netflix.spinnaker.orca.applications.tasks.UpsertApplicationTask$performRequest.callCurrent(Unknown Source)
[spin-orca-0] at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
[spin-orca-0] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
[spin-orca-0] at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
[spin-orca-0] at com.netflix.spinnaker.orca.front50.tasks.AbstractFront50Task.execute(AbstractFront50Task.groovy:67)
[spin-orca-0] at com.netflix.spinnaker.orca.batch.TaskTasklet.doExecuteTask(TaskTasklet.groovy:196)
[spin-orca-0] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[spin-orca-0] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[spin-orca-0] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[spin-orca-0] at java.lang.reflect.Method.invoke(Method.java:498)
[spin-orca-0] at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
[spin-orca-0] at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
[spin-orca-0] at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
[spin-orca-0] at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
[spin-orca-0] at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:923)
[spin-orca-0] at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:906)
[spin-orca-0] at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:74)
[spin-orca-0] at com.netflix.spinnaker.orca.batch.TaskTasklet$_executeTask_closure9.doCall(TaskTasklet.groovy:217)
[spin-orca-0] at com.netflix.spinnaker.orca.batch.TaskTasklet$_executeTask_closure9.call(TaskTasklet.groovy)
[spin-orca-0] at com.netflix.spinnaker.security.AuthenticatedRequest.lambda$propagate$1(AuthenticatedRequest.java:66)
[spin-orca-0] at com.netflix.spinnaker.orca.batch.TaskTasklet.executeTask(TaskTasklet.groovy:216)
[spin-orca-0] at com.netflix.spinnaker.orca.batch.TaskTasklet.execute(TaskTasklet.groovy:96)
[spin-orca-0] at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
[spin-orca-0] at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
[spin-orca-0] at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
[spin-orca-0] at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
[spin-orca-0] at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
[spin-orca-0] at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
[spin-orca-0] at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
[spin-orca-0] at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
[spin-orca-0] at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
[spin-orca-0] at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:198)
[spin-orca-0] at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
[spin-orca-0] at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:64)
[spin-orca-0] at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
[spin-orca-0] at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:165)
[spin-orca-0] at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
[spin-orca-0] at org.springframework.batch.core.job.flow.support.state.FlowState.handle(FlowState.java:55)
[spin-orca-0] at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:165)
[spin-orca-0] at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
[spin-orca-0] at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:134)
[spin-orca-0] at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:304)
[spin-orca-0] at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
[spin-orca-0] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[spin-orca-0] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[spin-orca-0] at java.lang.Thread.run(Thread.java:745)
[spin-orca-0] 2017-06-05 17:13:21.892  INFO 1 --- [hTaskExecutor-1] c.n.s.o.a.tasks.UpsertApplicationTask    : [] Orchestration:7f7f6590-0ab0-4001-80f0-a00de419e94e:0 createApplication SUCCEEDED -- Batch step id: 2,  Task Outputs: {
[spin-orca-0] "notification.type" : "upsertapplication",
[spin-orca-0] "application.name" : "test4",
[spin-orca-0] "previousState" : { },
[spin-orca-0] "newState" : {
[spin-orca-0] "name" : "test4",
[spin-orca-0] "description" : "test4",
[spin-orca-0] "email" : "itinfradevops@example.com",
[spin-orca-0] "updateTs" : null,
[spin-orca-0] "createTs" : null,
[spin-orca-0] "platformHealthOnly" : null,
[spin-orca-0] "platformHealthOnlyShowOverride" : null,
[spin-orca-0] "user" : "user1",
[spin-orca-0] "requiredGroupMembership" : [ ],
[spin-orca-0] "instancePort" : null,
[spin-orca-0] "cloudProviders" : "kubernetes"
[spin-orca-0] }
[spin-orca-0] },  Stage Context: {
[spin-orca-0] "requisiteStageRefIds" : [ ],
[spin-orca-0] "refId" : "0",
[spin-orca-0] "application" : {
[spin-orca-0] "cloudProviders" : "kubernetes",
[spin-orca-0] "instancePort" : null,
[spin-orca-0] "name" : "test4",
[spin-orca-0] "email" : "itinfradevops@example.com",
[spin-orca-0] "description" : "test4"
[spin-orca-0] },
[spin-orca-0] "user" : "user1",
[spin-orca-0] "stageDetails" : {
[spin-orca-0] "name" : null,
[spin-orca-0] "type" : "createApplication",
[spin-orca-0] "startTime" : 1496682797584,
[spin-orca-0] "isSynthetic" : false
[spin-orca-0] }
[spin-orca-0] }
[spin-orca-0] 2017-06-05 17:13:21.986  INFO 1 --- [hTaskExecutor-1] c.n.s.o.l.StageTaskPropagationListener   : [] Setting task status to SUCCEEDED (stageId: eea1c7bc-78e9-40a9-8dd7-858cf0903de8, taskId: 1, taskName: createApplication) [afterTask]
[spin-orca-0] 2017-06-05 17:13:22.027  INFO 1 --- [hTaskExecutor-1] c.n.spinnaker.orca.echo.EchoService      : [] ---> HTTP POST http://spin-echo:8089/
[spin-orca-0] 2017-06-05 17:13:22.034  INFO 1 --- [hTaskExecutor-1] c.n.spinnaker.orca.echo.EchoService      : [] <--- HTTP 200 http://spin-echo:8089/ (6ms)
[spin-orca-0] 2017-06-05 17:13:22.075  INFO 1 --- [hTaskExecutor-1] c.n.s.o.l.ExecutionPropagationListener   : [] Marked 7f7f6590-0ab0-4001-80f0-a00de419e94e as SUCCEEDED (afterJob)
[spin-orca-0] 2017-06-05 17:13:22.113  INFO 1 --- [hTaskExecutor-1] o.s.b.c.l.support.SimpleJobLauncher      : [] Job: [FlowJob: [name=Orchestration:test4:7f7f6590-0ab0-4001-80f0-a00de419e94e]] completed with the following parameters: [{orchestration=7f7f6590-0ab0-4001-80f0-a00de419e94e, application=test4, timestamp=1496682796615}] and the following status: [COMPLETED]
```

**Comment by emptywee** [comment]
Spinnaker version:
        - image: quay.io/spinnaker/clouddriver:v1.628.0
        - image: quay.io/spinnaker/deck:v2.1121.0
        - image: quay.io/spinnaker/echo:v1.136.0
        - image: quay.io/spinnaker/fiat:v0.26.0
        - image: quay.io/spinnaker/front50:v1.98.0
        - image: quay.io/spinnaker/gate:v3.40.1
        - image: quay.io/spinnaker/igor:v1.71.0
        - image: quay.io/spinnaker/orca:v2.8.8
        - image: quay.io/spinnaker/orca:v1.394.0

**Comment by ttomsu** [comment]
Closing this now. Please let me know if you're still seeing issues (FYI @msloes)

**Comment by emptywee** [comment]
Will check once the new image is released on Quay. Thanks @ttomsu !
